CREATE TABLE [dbo].[silver_starratings] (

	[service_name] varchar(8000) NULL, 
	[provider_name] varchar(8000) NULL, 
	[service_suburb] varchar(8000) NULL, 
	[ownership] varchar(8000) NULL, 
	[acpr_name] varchar(8000) NULL, 
	[state] varchar(8000) NULL, 
	[mmm_region] varchar(8000) NULL, 
	[mmm_code] varchar(8000) NULL, 
	[size] varchar(8000) NULL, 
	[overall_rating] bigint NULL, 
	[re_rating] bigint NULL, 
	[compliance_rating] bigint NULL, 
	[staffing_rating] bigint NULL, 
	[rn_care_min_target] bigint NULL, 
	[rn_care_min_actual] bigint NULL, 
	[total_care_min_target] bigint NULL, 
	[total_care_min_actual] bigint NULL, 
	[qm_rating] bigint NULL, 
	[qm_pressure_injuries] bigint NULL, 
	[qm_restrictive_practices] bigint NULL, 
	[qm_weight_loss] bigint NULL, 
	[qm_falls] bigint NULL, 
	[qm_major_injury] bigint NULL, 
	[qm_polypharmacy] bigint NULL, 
	[qm_antipsychotic] bigint NULL
);